### PR TITLE
README.md: Coala -> coala

### PR DESCRIPTION
**Pull request by tushar-rishav**
It seems there has been a misunderstanding in https://github.com/mrjoelkemp/awesome-paid-open-source/pull/22 . *coala* startswith small *c* and not capital. 
We hope it gets solved with this PR.
Thanks again!

CC @sils1297 @mrjoelkemp

### CODE REVIEW

**Comment by sils1297** [comment]
ahm could we maybe say that they're sponsoring build capacity?

**Comment by mrjoelkemp** [comment]
Thanks. All of the other projects are capitalized. To keep with the formatting, we capitalized the project's name. If you started a sentence with the project's name, it would also be capitalized. 

Please let me know if this is a deal breaker. I'll close this PR as a wontfix. Hopefully, the reasoning is clear.

**Comment by sils1297** [comment]
Actually we would always write coala with a lower case c, even at the beginning of the sentence.

**Comment by rnicholus** [comment]
Hmm, sounds like "jQuery", amirite?

**Comment by sils1297** [comment]
jep

**Comment by sils1297** [comment]
We definitely have it somewhere in the docs and we even have a code analysis routine for it to enforce it - coala is always written with a lower case c, even in the beginnings of sentences :)

**Pull request closed without merging**
