### PR TITLE
Add plotly.js and the Plotly commercial open source model

### PR DESCRIPTION
**Pull request by chriddyp**
Really great list, thank you for compiling!

At Plotly, we've made our core open source technology open source. We build products on top of the library as well as allow companies to directly fund features. I thought this would be a worthy addition!

### CODE REVIEW

**Comment by rnicholus** [comment]
Plotly.js is MIT licensed and entirely free to use, while the service built on top of the library has a free "community" tier (similar to Travis-CI), with paid options for everyone else. Am I correct?

**Comment by chriddyp** [comment]
That's correct @rnicholus ! It might also be notable that we fund some of the open source plotly.js work directly from corporate sponsorships.

**Comment by mrjoelkemp** [comment]
Sounds good

**Comment by chriddyp** [comment]
Good suggestion. Just updated

**Comment by rnicholus** [comment]
Thanks!

**Pull request merged**
