### PR TITLE
react-boilerplate is sponsored via open collective

### PR DESCRIPTION
**Pull request by mxstbr**

### CODE REVIEW

**Comment by mrjoelkemp** [comment]
Thanks for contributing @mxstbr! I'll fix up the PR before merging.

**Comment by mrjoelkemp** [comment]
Merged. Thanks again!

**Comment by mxstbr** [comment]
Ah, sorry for the troubles! 😅

**Comment by mrjoelkemp** [comment]
No trouble at all. Thanks a ton for contributing. Didn't know react-boilerplate was funded. That's awesome. This list could use more small/indie projects that have sought community funding.

**Pull request closed without merging**
